
import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../Components/Header";
import Footer from '@/Components/Footer';

export const metadata = {
  title: 'فروشگاه فایل مرن فا',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
